#!/usr/bin/env node

var Instances = require('./lib/instances');
	config = require('./config.json');

var options = config.futuregrid;
var instances = new Instances(options);

instances.get(function(err, result) {
	if (err) {
		return console.log(err);
	}

	console.log(result);
});
