#!/usr/bin/env node

var commandLine = require('commander'),
	Instances = require('./lib/instances'),
	config = require('./config.json'),
	sprintf = require('sprintf-js').sprintf,
	fs = require('fs');

var options = getOptions();
validateOptons(options);

var instances = new Instances(config.futuregrid);

instances.get(function(err, results) {
	if (err) {
		return console.log(err);
	}

	var matches = []
	results.forEach(function(result) {
		if (result.hasOwnProperty('imageId') && result.imageId === options.imageId) {
			if (options.keyName) {
				if (result.hasOwnProperty('keyName') && result.keyName === options.keyName) {
					matches.push(result);	
				}
			} else {
				matches.push(result);
			}
		}
	});

	printResults(matches);
	writeResults(matches);
});

function printResults(results) {
	var keys = ['instanceId', 'imageId', 'keyName', 'instanceType', 'ipAddress', 'privateIpAddress'];
	var header = '';
	var border = '';
	var width = 17;
	var format = '%-' + width + 's| ';
	var borderFormat = "%+'-" + (width + 2) + "s"

	keys.forEach(function(key){
		header += sprintf(format, key);	
		border += sprintf(borderFormat, '   ');
	});
	console.log(header);
	console.log(border);

	results.forEach(function(result){
		var line = '';
		keys.forEach(function(key){
			line += sprintf(format, result[key]);	
		});	
		console.log(line);
	});
}

function writeResults(results) {
	fs.writeFile('instances.json', JSON.stringify(results), function(err) {
		if (err) {
			console.log(err);
		}
	})
}

function getOptions() {
	commandLine
		.version('0.0.1')
		.description('Used to get the instances that match a pattern and write them to a file.')
		.option('--imageId <imageId>', 'The image id used to filter the search.')
		.option('--keyName <keyName>', 'The keyName used to filter the search.')

	commandLine.parse(process.argv);
	return commandLine;
}

function validateOptons(options) {
	validateRequired(options, 'imageId');
}

function validateRequired(options, key) {
	if (!options[key]) {
		console.log('Missing required param: ' + key);
		options.help();
	}
}
